pipeline {
    agent any

    parameters {
        string(name: 'vendor', defaultValue: 'vendor', description: 'vendor name')
    }

    environment {
        AWS_DEFAULT_REGION="us-east-1"
        awsCredentials = credentials('awsCredentials')
    }
    
    stages {

        stage ("test stage") {
            steps {
                sh '''
                aws ec2 describe-instances
                '''
            }
        }

        stage('checkout') {
            steps {
                 git branch: 'main', credentialsId: 'c8d323bf-fe34-4694-b2b2-2de9783744d4', url: 'https://github.com/prale/projects.git'
                }
            }
        
        stage ("terraform init") {
            steps {
                dir('final_pro'){
                    sh 'terraform init'
                }
            }
        }
         
        stage ("terraform plan") {
            steps {
                dir('final_pro'){
                    sh "terraform plan -var 'vendor_name=${params.vendor}'"
                }
            }
        }
       /*
        stage ("terraform apply") {
            steps {
                sh "terraform apply""
            }
        }
        
        stage ("terraform show") {
            steps {
                sh "terraform show"
            }
        }
        */
    }
}