pipeline {

   agent any

   options {
      ansiColor('xterm')
   }

   environment {
      AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
      AWS_REGION = credentials('aws_region')
      AWS_DEFAULT_REGION = credentials('aws_region')
      AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
      TF_IN_AUTOMATION = "true"
      AWS_ACCOUNT = credentials('aws_account')
      // TF_LOG = "TRACE"
   }

   stages {

      stage('CLEAN WORKING DIR & GIT CHECKOUT') {
         steps {
               cleanWs()  
               checkout scm
         }
      }

      stage('Terraform INIT') {
         steps {
               echo 'Terraform INIT...'
               dir('pro/'){
                  sh "terraform init"
               }                
         }
      }

      stage('Terraform PLAN') {
         steps {
               echo 'Terraform PLAN...'
               dir('pro/'){
                  sh "terraform plan"
               }                
         }
      }

      stage('Terraform APPLY') {
         steps {
               echo 'Terraform APPLY...'
               dir('pro/'){
                  sh "terraform apply -auto-approve"
               }                
         }
      }

      stage('Terraform SHOW') {
         steps {
               echo 'Terraform SHOW...'
               dir('pro/'){
                  sh "terraform show"
               }                
         }
      }

      stage('Terraform DESTROY') {
         steps {
               echo 'Terraform DESTROY...'
               dir('pro/'){
                  sh "terraform destroy -auto-approve"
               }                
         }
      }

   }
}